// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zwierzatka.Models;

#nullable disable

namespace Zwierzatka.Migrations
{
    [DbContext(typeof(ZwierzatkaDbContext))]
    [Migration("20250613195654_wynik1")]
    partial class wynik1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zwierzatka.Models.Uzytkownik", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("haslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("typ")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("uzytkownicy");

                    b.HasData(
                        new
                        {
                            id = 1,
                            haslo = "haslo",
                            nazwa = "jusin",
                            typ = 0
                        },
                        new
                        {
                            id = 2,
                            haslo = "maslo",
                            nazwa = "Mamut",
                            typ = 0
                        });
                });

            modelBuilder.Entity("Zwierzatka.Models.Zwierze", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notatki")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rasa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("uzytkownikId")
                        .HasColumnType("int");

                    b.Property<int>("wiek")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("zwierzeta");

                    b.HasData(
                        new
                        {
                            id = 1,
                            imie = "Tropik",
                            notatki = "Pies Jusina",
                            rasa = "pies polski",
                            uzytkownikId = 1,
                            wiek = 6
                        },
                        new
                        {
                            id = 2,
                            imie = "Frodo",
                            notatki = "Kot",
                            rasa = "Ragdoll",
                            uzytkownikId = 2,
                            wiek = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
